### ISSUE TITLE
Hai Rizda

### ISSUE THREAD

**Issue by adibwafi** [rizdaprasetya/Raw-Domain-Extension-Price#3]
Hai Rizda

**Comment by rizdaprasetya** [comment]
> Hai Rizda

Eh ada Adib, hai Dib 😂

**Comment by adibwafi** [comment]
accept linkedin bisa kali da

**Comment by rizdaprasetya** [comment]
Bole bole ntar dib, sorry jarang buka Linkedin 😅

**Comment by adibwafi** [comment]
Mau dong berguru programming da wk

**Comment by rizdaprasetya** [comment]
> Mau dong berguru programming da wk

Haha cupu gw mah kalo soal pure programming, boleh kalo mau sharing2, kontak2 aja WA/Line dib nomor gw blm pernah ganti masih yg dulu. Kalo sosmed lain gw jarang/mager ngecek 😂

**Comment by rizdaprasetya** [comment]
Agak surprising sekarang lu pindah jalur ke programming, come to the dark side 😂

**Comment by adibwafi** [comment]
> pernah

nahitu sejak ganti hape kontak lama ilang da, github bisa di PM ga ya? mau ijin tanya koding wk
