### ISSUE TITLE
.org listed twice

### ISSUE THREAD

**Issue by mwt** [rizdaprasetya/Raw-Domain-Extension-Price#8]
Any idea what this \$4.71 price is in the Cloudflare dump? Is there some way in which that price is also real in addition to the \$9.93 price.

**Comment by rizdaprasetya** [comment]
Good catch, & thanks for letting me know.
The cheaper one is valid, but it's supposed to be for `.org.uk`.

It was a bug in my script, unhandled scenario when the domain contains >2
dots, it would only output the text before 2nd dots. I plan to fix
tomorrow. It's about time for me to update the dump too anyway while I'm at
it.

**Comment by rizdaprasetya** [comment]
Fixed now https://github.com/rizdaprasetya/Raw-Domain-Extension-Price/commit/b7f9f5d53933955c59a0406c7f270030b8966825 . You can check the [updated table](https://github.com/rizdaprasetya/Raw-Domain-Extension-Price?tab=readme-ov-file#embedded-raw-domain-extension-price-table-dump). 
Thanks @mwt ! closing this.

Note: you do have some very interesting contents & projects, i'll be checking some of those!
